class BaseNormalizer:
    def normalize_inbound_account(self, account) -> None: ...
    def normalize_inbound_block_hash(self, block_hash) -> None: ...
    def normalize_inbound_block_number(self, block_number) -> None: ...
    def normalize_inbound_filter_id(self, filter_id) -> None: ...
    def normalize_inbound_filter_params(self, from_block, to_block, address, topics) -> None: ...
    def normalize_inbound_log_entry(self, log_entry) -> None: ...
    def normalize_inbound_private_key(self, private_key) -> None: ...
    def normalize_inbound_raw_transaction(self, raw_transaction_hex) -> None: ...
    def normalize_inbound_storage_slot(self, storage_slot) -> None: ...
    def normalize_inbound_timestamp(self, timestamp) -> None: ...
    def normalize_inbound_transaction(self, transaction) -> None: ...
    def normalize_inbound_transaction_hash(self, transaction_hash) -> None: ...
    def normalize_outbound_account(self, accounts) -> None: ...
    def normalize_outbound_account_list(self, account_list) -> None: ...
    def normalize_outbound_balance(self, account) -> None: ...
    def normalize_outbound_block_hash(self, block_hash) -> None: ...
    def normalize_outbound_block(self, block) -> None: ...
    def normalize_outbound_code(self, account) -> None: ...
    def normalize_outbound_filter_id(self, filter_id) -> None: ...
    def normalize_outbound_log_entry(self, log_entry) -> None: ...
    def normalize_outbound_gas_estimate(self, gas_estimate) -> None: ...
    def normalize_outbound_nonce(self, account) -> None: ...
    def normalize_outbound_receipt(self, receipt) -> None: ...
    def normalize_outbound_return_data(self, data) -> None: ...
    def normalize_outbound_transaction(self, transaction) -> None: ...
    def normalize_outbound_transaction_hash(self, transaction_hash) -> None: ...
