from collections.abc import Generator

from _typeshed import Incomplete
from eth_tester.utils.encoding import int_to_32byte_big_endian as int_to_32byte_big_endian

def normalize_dict(value, normalizers) -> Generator[Incomplete, None, None]: ...
def normalize_array(value, normalizer) -> Generator[Incomplete, None, None]: ...
def normalize_if(value, conditional_fn, normalizer): ...
def to_integer_if_hex(value): ...
def int_to_32byte_hex(value): ...
