from typing import Any

from eth.abc import BlockAPI

def get_pyevm_version(): ...
def is_supported_pyevm_version_available(): ...

class BlockAPI: ...

def is_london_block(block: dict[str, Any] | BlockAPI) -> bool: ...
def is_shanghai_block(block: dict[str, Any] | BlockAPI) -> bool: ...
def is_cancun_block(block: dict[str, Any] | BlockAPI) -> bool: ...
