class BaseValidator:
    def validate_inbound_account(self, account) -> None: ...
    def validate_inbound_storage_slot(self, account) -> None: ...
    def validate_inbound_block_hash(self, block_hash) -> None: ...
    def validate_inbound_block_number(self, block_number) -> None: ...
    def validate_inbound_filter_id(self, filter_id) -> None: ...
    def validate_inbound_filter_params(self, from_block, to_block, address, topics) -> None: ...
    def validate_inbound_private_key(self, private_key) -> None: ...
    def validate_inbound_raw_transaction(self, raw_transaction_hex) -> None: ...
    def validate_inbound_timestamp(self, timestamp) -> None: ...
    def validate_inbound_transaction(self, transaction, txn_internal_type) -> None: ...
    def validate_inbound_transaction_hash(self, transaction_hash) -> None: ...
    def validate_outbound_accounts(self, accounts) -> None: ...
    def validate_outbound_balance(self, account) -> None: ...
    def validate_outbound_block_hash(self, block_hash) -> None: ...
    def validate_outbound_block(self, block) -> None: ...
    def validate_outbound_code(self, account) -> None: ...
    def validate_outbound_gas_estimate(self, gas_estimate) -> None: ...
    def validate_outbound_log_entry(self, log_entry) -> None: ...
    def validate_outbound_nonce(self, account) -> None: ...
    def validate_outbound_receipt(self, receipt) -> None: ...
    def validate_outbound_return_data(self, data) -> None: ...
    def validate_outbound_transaction(self, transaction) -> None: ...
    def validate_outbound_transaction_hash(self, transaction_hash) -> None: ...
