from _typeshed import Incomplete
from eth_tester.constants import UINT8_MAX as UINT8_MAX
from eth_tester.constants import UINT64_MAX as UINT64_MAX
from eth_tester.constants import UINT256_MAX as UINT256_MAX
from eth_tester.exceptions import ValidationError as ValidationError
from eth_typing import HexStr as HexStr

def validate_positive_integer(value) -> None: ...
def validate_uint(max_val, value) -> None: ...

validate_uint256: Incomplete
validate_uint64: Incomplete
validate_uint8: Incomplete

def validate_bytes(value) -> None: ...
def validate_text(value) -> None: ...
def validate_is_dict(value) -> None: ...
def validate_is_list_like(value) -> None: ...
def validate_any(value, validators) -> None: ...
def validate_no_extra_keys(value, allowed_keys) -> None: ...
def validate_has_required_keys(value, required_keys) -> None: ...
def validate_dict(value, key_validators) -> None: ...
def validate_array(value, validator) -> None: ...
def validate_transaction_type(value) -> None: ...
def if_not_null(validator_fn): ...
def if_not_create_address(validator_fn): ...
def validate_address(value: str | HexStr | bytes): ...
