name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "run Pytest tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
    - name: isort
      run: |
        isort . --check --diff
    - name: black
      if: always()
      run: |
        black . --check --diff
    - name: pyright
      if: always()
      run: |
        basedpyright
    - name: Run tests
      if: always()
      run: |
        pytest
